/**
 * icon references can be found here: https://fontawesome.com/icons?d=gallery&m=pro
 */

import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faChevronRight,
    faChevronUp,
    faChevronDown,
    faBuilding,
    faUserCircle,
    faArrowRight,
    faReply,
    faPrint,
    faDownload,
    faPennant
} from '@fortawesome/pro-solid-svg-icons';
import {
    faBell,
    faSignOut,
    faArrowAltFromLeft,
    faArrowAltToLeft,
    faChartLine,
    faCogs,
    faKey,
    faHandsHelping,
    faChevronRight as faCRReg,
    faChevronLeft,
    faChevronDoubleLeft,
    faChevronDoubleRight,
    faThumbtack,
    faPlus,
    faTimes,
    faTrash,
    faTag,
    faMapMarker,
    faEdit,
    faDraftingCompass,
    faCheckCircle,
    faStickyNote,
    faImage,
    faImages,
    faHandshake,
    faHistory,
    faTasks,
    faUser
} from '@fortawesome/pro-regular-svg-icons';

library.add(
    faCRReg,
    faChevronDoubleLeft,
    faChevronDoubleRight,
    faChevronLeft,
    faChevronRight,
    faChevronUp,
    faChevronDown,
    faBuilding,
    faChartLine,
    faKey,
    faHandsHelping,
    faBell,
    faUser,
    faUserCircle,
    faSignOut,
    faArrowAltFromLeft,
    faArrowAltToLeft,
    faCogs,
    faThumbtack,
    faPlus,
    faTimes,
    faTrash,
    faTag,
    faArrowRight,
    faReply,
    faMapMarker,
    faEdit,
    faDraftingCompass,
    faCheckCircle,
    faStickyNote,
    faImage,
    faImages,
    faHandshake,
    faHistory,
    faTasks,
    faPrint,
    faDownload,
    faPennant
);
